# Generated by Django 5.2.1 on 2025-10-25 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='titel',
            new_name='title',
        ),
    ]
